# Everforest theme converted from kitty/colors/Everforest.conf
foreground = #b4b9bc
background = #121b1c
cursor-color = #b4b9bc

palette = 0=#121b1c
palette = 1=#5A6669
palette = 2=#6B6D70
palette = 3=#8D706F
palette = 4=#728970
palette = 5=#928C7A
palette = 6=#717B83
palette = 7=#b4b9bc
palette = 8=#7d8183
palette = 9=#5A6669
palette = 10=#6B6D70
palette = 11=#8D706F
palette = 12=#728970
palette = 13=#928C7A
palette = 14=#717B83
palette = 15=#b4b9bc
